[project]
name = "climbinggame"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gym>=0.26.2",
    "numpy>=2.4.2",
    "selenium>=4.40.0",
]
